version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_multilingual
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    profiles:
      - cpu
      - gpu

  # Ollama service (optional, if running Ollama in Docker)
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama_deepseek
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./ollama_models:/root/.ollama
  #   restart: unless-stopped
  #   profiles:
  #     - cpu
  #     - gpu
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   # Remove deploy section above for CPU-only

volumes:
  qdrant_storage:
  ollama_models:

